repository:
  topics: ["testorg", "infrastructure-as-code", "safe-settings"]
  has_issues: true
  has_projects: true
  has_wiki: false

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions:
        users: []
        teams: []