repositories:
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false
  allow_update_branch: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  has_issues: false
  has_projects: false
  merge_commit_title: PR_TITLE
  merge_commit_message: PR_BODY
