# Organization-wide repository defaults for Safe-Settings
# https://github.com/probot/safe-settings
# See also: https://docs.github.com/en/organizations/managing-organization-settings/repository-defaults-and-branch-protection


# END OF FILE
