# Organization-wide repository defaults for Safe-Settings
# https://github.com/probot/safe-settings
# See also: https://docs.github.com/en/organizations/managing-organization-settings/repository-defaults-and-branch-protection

repository_defaults:
  # Branch settings
  default_branch: main                            # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/changing-the-default-branch

  # Merge options
  allow_squash_merge: false                       # Allow squash merging
  allow_merge_commit: true                        # Allow merge commits
  allow_rebase_merge: false                       # Allow rebase merging

  merge_commit_message: "PR_TITLE_AND_BODY"       # Use PR title and description for merge commit message
  merge_commit_title: "PR_TITLE"                  # Use PR title for commit title
  squash_merge_commit_message: "PR_BODY"          # Use PR body for squash commit message
  squash_merge_commit_title: "PR_TITLE"           # Use PR title for squash commit title
  rebase_merge_commit_message: "PR_TITLE_AND_BODY"# Use PR title and body for rebase commit message
  rebase_merge_commit_title: "PR_TITLE"           # Use PR title for rebase commit title

  # PR/branch workflow
  delete_branch_on_merge: true                    # Automatically delete branch after merge: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges#about-automatic-branch-deletion
  enable_auto_merge: false                        # Enable auto-merge for PRs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/enabling-auto-merge-for-pull-requests
  always_suggest_update_branch: true              # Suggest updating PR branch, but do not require: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/automatically-updating-branches-before-merging-a-pull-request
  close_issues_via_pr: false                      # Do not auto-close issues when merging PRs: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

  # Branch protection rules
  branch_protection:
    main:
      required_status_checks:
        strict: false                             # Do not require branch to be up to date before merging
        contexts: []                             # List required status checks (add CI checks here!)
      enforce_admins: true                       # Enforce branch protection for admins
      required_pull_request_reviews:
        required_approving_review_count: 3       # Require at least 1 review approval
        require_code_owner_reviews: true         # Require code owner review: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
        require_last_push_approval: true         # Require approval of most recent push
        require_conversation_resolution: true    # Require all code conversations to be resolved before merging
        dismissal_restrictions:
          users: []                             # Users allowed to dismiss reviews
          teams: []                             # Teams allowed to dismiss reviews
      allow_force_pushes: false                  # Disallow force pushes
      allow_deletions: false                     # Disallow branch deletion
      require_linear_history: false              # Do not require linear history (set true to enforce rebase workflow)
      required_signatures: false                 # Do not require signed commits
      restrict_pushes: false                     # Do not restrict who can push
      restrict_deletions: true                   # Restrict deletions (sometimes redundant with allow_deletions)
      require_code_scanning: false               # Do not require code scanning (set true if you use CodeQL or similar)

organization:
  repository_rulesets:
    main:
      name: "main"                              # Ruleset name for identification
      target_branches: ["main"]                 # Branches this ruleset applies to
      restrict_deletions: true                  # Prevent branch deletion
      require_pull_request: true                # Require PR before merging
      required_approving_review_count: 1        # Require at least 1 approval
      require_code_owner_reviews: true          # Code owner review required
      require_last_push_approval: true          # Most recent push must be approved
      require_conversation_resolution: true     # All conversations must be resolved
      allowed_merge_methods: ["merge"]          # Only allow merge commits
      require_status_checks: []                 # List required status checks (add CI checks here!)
      require_up_to_date_before_merge: false    # Only suggest updating branch, do not require
      block_force_pushes: true                  # Block force pushes
      bypass_teams: []                         # Teams allowed to bypass rules
      require_linear_history: false             # Do not require linear history
      require_code_scanning: false              # Do not require code scanning
      restrict_pushes: false                    # Do not restrict who can push

# END OF FILE
